import type { Metadata } from "next";
import { siteConfig } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Terms of Service for ${siteConfig.name}`,
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
      <h1 className="mb-8 text-3xl font-bold text-gray-900 dark:text-white">
        Terms of Service
      </h1>
      <div className="space-y-6 text-gray-600 dark:text-gray-400">
        <p>Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

        <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
          Acceptance of Terms
        </h2>
        <p>
          By accessing and using {siteConfig.name}, you accept and agree to be
          bound by these Terms of Service.
        </p>

        <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
          Description of Service
        </h2>
        <p>
          {siteConfig.name} provides free online developer and text utility
          tools. All tools run entirely in your web browser. We do not process,
          store, or transmit any data you input into our tools.
        </p>

        <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
          Disclaimer of Warranties
        </h2>
        <p>
          The tools and services are provided &quot;as is&quot; without warranty
          of any kind, express or implied. We do not guarantee the accuracy,
          completeness, or reliability of any tool output.
        </p>

        <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
          Limitation of Liability
        </h2>
        <p>
          In no event shall {siteConfig.name} be liable for any indirect,
          incidental, special, or consequential damages arising from the use of
          our tools.
        </p>

        <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
          Intellectual Property
        </h2>
        <p>
          The content, design, and code of this website are the property of{" "}
          {siteConfig.name}. You may use the tools for personal and commercial
          purposes. Output generated by the tools belongs to you.
        </p>

        <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
          Changes to Terms
        </h2>
        <p>
          We reserve the right to modify these terms at any time. Continued use
          of the website after changes constitutes acceptance of the new terms.
        </p>
      </div>
    </div>
  );
}
